### ISSUE TITLE
Redis connection can not be reopened after the remote server has closed it

### ISSUE THREAD

**Issue by eroteev** [yiisoft/yii2-redis#71] opened 2016-06-03 16:09 UTC
### What steps will reproduce the problem?
1. Connect to remote server.
2. Wait enough time so the remote server closes the connection on their side.
3. Try to execute redis command. 

### What's expected?
The connection to be reopened.

### What do you get instead?
Exception: fwrite(): send of 52 bytes failed with errno=32 Broken pipe

### Additional info

| Q                | A
| ---------------- | ---
| Yii vesion       | 206
| PHP version      | 5.6.10
| Operating system | Ubuntu 12.04

**Comment by cebe** [comment] 2016-06-06 10:14
duplicate of #57

**Closed by cebe** 2016-06-06 10:14 UTC
Labels: bug
