### ISSUE TITLE
How to use for cluster

### ISSUE THREAD

**Issue by Liv1020** [yiisoft/yii2-redis#90] opened 2016-12-05 02:49 UTC
### What steps will reproduce the problem?
no

### What's expected?
Use for cluster

### What do you get instead?
no

### Additional info

| Q                | A
| ---------------- | ---
| Yii vesion       |2.0.9
| PHP version      |5.6.28
| Operating system |windows

**Comment by cebe** [comment] 2016-12-05 02:54
duplicate of https://github.com/yiisoft/yii2-redis/issues/66

**Closed by cebe** 2016-12-05 02:54 UTC
